### ISSUE TITLE
Inconsistent use of terms in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [pattarinn/ku-polls#1]
### Requirements

> 3. The results of the poll can be verified both in **voting period** and after the closing date.
> 4. During the **polling period**, the poll taker can view and edit their selection any time.

Are the "voting period" and the "polling period" the same period? If they are, using the same terms could make it more clear. If they aren't, maybe some definition of the terms "voting period", "closing date" and "polling period" might be warranted.

Optionally, specifying *who* can do in addition to *what* also would make it more easily testable. For example, can unauthenticated users see the same things as authenticated users? Can they vote?

### English

> 2. A choice on poll items can be added.

"A choice" would imply only one choice can be added. Using the plural, "choices", would be better.

> 3. The results of the poll can be verified both in voting period and after the closing date.

"voting period" is a singular noun here and needs the article "the".

**Comment by pattarinn** [comment]
Thank you!
