### ISSUE TITLE
Repository has extra layer of directories

### ISSUE THREAD

**Issue by jbrucker** [pattarinn/ku-polls#2]
Your git repository has:
```
.gitignore
README.md
mysite/
          mysite/
          polls/
          manage.py
```
should be (as stated with example in the assignment!)
```
.gitignore
README.md
mysite/
polls/
manage.py
```
There is an extra layer of directories.
On some projects this is OK if that's the way the organization
wants it, but not what was requested here.

**Comment by pattarinn** [comment]
Remove extra layer of directories. Thanks for the reminding!
